include:
  - template: Auto-DevOps.gitlab-ci.yml

build:
  image: "node:12.16.1"
  script:
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - PATH=$PATH:$HOME/.cargo/bin
    - yarn
    - yarn build

test:
  image: "node:12.16.1"
  script:
    - yarn
    - yarn test
